// Mock数据 - 用于开发和测试
import type { NewsItem, DailyReport } from '@/lib/supabase';

export const mockNews: NewsItem[] = [
  {
    id: 'news-001',
    title: 'OpenAI发布GPT-5，性能全面超越现有模型',
    summary: 'OpenAI在今日凌晨发布了备受期待的GPT-5模型。该模型在各项基准测试中均取得了SOTA成绩，特别是在复杂推理和长文本理解方面表现突出。GPT-5支持128K上下文窗口，数学能力提升超过40%，代码生成质量接近专业程序员水平。',
    source: 'OpenAI',
    source_url: 'https://openai.com/blog/gpt-5',
    priority: 'SSS',
    category: '大模型',
    published_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-002',
    title: 'Anthropic Claude 4发布：更安全、更强大的AI助手',
    summary: 'Anthropic推出了Claude 4系列模型，包含Claude 4 Sonnet和Claude 4 Opus两个版本。新模型在保持安全性的同时大幅提升了各项能力，特别是在长文档分析、多步骤推理和创意写作方面。Claude 4 Opus在多项评测中超越了GPT-5。',
    source: 'Anthropic',
    source_url: 'https://www.anthropic.com/news/claude-4',
    priority: 'SSS',
    category: '大模型',
    published_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-003',
    title: 'Google DeepMind开源Gemma 3，性能接近GPT-4',
    summary: 'Google DeepMind宣布开源Gemma 3系列模型，这是继Gemma 2之后的最新版本。Gemma 3-27B版本在多项评测中表现接近GPT-4，同时保持了开源模型的灵活性。Google还发布了配套的工具链和微调指南。',
    source: 'Google DeepMind',
    source_url: 'https://deepmind.google/blog/gemma-3',
    priority: 'SS',
    category: '开源',
    published_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-004',
    title: 'Meta推出Llama 4多模态版本，支持视频理解',
    summary: 'Meta AI发布了Llama 4系列，其中Llama 4-Vision版本支持图像和视频理解能力。新模型延续了Llama系列的开源传统，提供了从7B到405B的多种规格。Meta表示这是目前最强的开源多模态模型。',
    source: 'Meta AI',
    source_url: 'https://ai.meta.com/blog/llama-4',
    priority: 'SS',
    category: '大模型',
    published_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-005',
    title: 'Mistral AI发布Mistral Large 2，上下文窗口达256K',
    summary: 'Mistral AI推出了Mistral Large 2模型，这是其旗舰产品的重大更新。新模型支持256K上下文窗口，在长文本理解方面大幅提升。同时Mistral AI还发布了专门针对代码优化的Mistral Codestral 2。',
    source: 'Mistral AI',
    source_url: 'https://mistral.ai/news/mistral-large-2',
    priority: 'S',
    category: '大模型',
    published_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-006',
    title: '百度文心大模型4.0 Turbo发布，推理速度提升3倍',
    summary: '百度在WAVE SUMMIT开发者大会上发布了文心大模型4.0 Turbo版本。该版本在保持高质量输出的同时，推理速度提升3倍，成本降低50%。百度还宣布了文心一言用户突破1亿的重磅消息。',
    source: '百度',
    source_url: 'https://wenxin.baidu.com/blog/wenxin-4-turbo',
    priority: 'S',
    category: '大模型',
    published_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-007',
    title: '阿里通义千问开源Qwen2.5系列，包含72B旗舰版本',
    summary: '阿里云开源了Qwen2.5系列模型，包含从0.5B到72B的多种规格。其中Qwen2.5-72B-Instruct在多项评测中表现优异，特别是在中文任务上领先其他开源模型。阿里还发布了配套的预训练和微调工具。',
    source: '阿里云',
    source_url: 'https://qwenlm.github.io/blog/qwen2.5',
    priority: 'S',
    category: '开源',
    published_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-008',
    title: '字节跳动发布豆包大模型1.5，号称性价比最高',
    summary: '字节跳动在火山引擎大会上发布了豆包大模型1.5版本。该版本主打高性价比，API价格仅为行业平均水平的1/10。豆包1.5在中文理解和生成方面表现优异，特别适合内容创作和客服场景。',
    source: '字节跳动',
    source_url: 'https://www.volcengine.com/blog/doubao-1.5',
    priority: 'A',
    category: '大模型',
    published_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockDailyReport: DailyReport = {
  id: 'report-001',
  date: new Date().toISOString().split('T')[0],
  period: 'morning',
  news: mockNews,
  headline: 'GPT-5和Claude 4同日发布，AI竞争进入新阶段',
  created_at: new Date().toISOString(),
};
